import { Usuario } from './usuario';

export const USUARIOS: Usuario[] = [
    //Objetos con formato JSON
    {id:1, 
        username: 'Bibi', 
        password: 'bbbbbb', 
        email:  'bibi@gmail.com', 
        name: 'Bibi', 
        phone: '1111', 
        photo: 'ruta1', 
        create_at: new Date('2024-01-01'), 
        enabled: true, 
        roles:[]
    },
    {id:2, 
        username: 'Henry', 
        password: 'hhhhh', 
        email:  'henry@gmail.com', 
        name: 'Henry', 
        phone: '2222', 
        photo: 'ruta2', 
        create_at: new Date('2024-01-01'), 
        enabled: true, 
        roles:[]},
    {id:3, 
        username: 'Bibi', 
        password: 'ddddd', 
        email:  'david@gmail.com', 
        name: 'David', 
        phone: '3333', 
        photo: 'ruta3', 
        create_at: new Date('2024-01-01'), 
        enabled: true, 
        roles:[]},
    {id:4, 
        username: 'Bibi', 
        password: 'kkkkk', 
        email:  'miguel@gmail.com', 
        name: 'Miguel', 
        phone: '4444', 
        photo: 'ruta4', 
        create_at: new Date('2024-01-01'), 
        enabled: true, 
        roles:[]},
    {id:5, 
        username: 'Bibi', 
        password: 'mmmmm', 
        email:  'margarita@gmail.com', 
        name: 'Margarita', 
        phone: '5555', 
        photo: 'ruta5', 
        create_at: new Date('2024-01-01'), 
        enabled: true, 
        roles:[]},
]